default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: katie
  password: 040846
  pool: 5

development:
  <<: *default
  database: todo_list_development #db_name_development

test:
  <<: *default
  database: todo_list_test #db_name_development

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  
#คอมเม้นไว้ก่อนยังไม่สร้าง dev ตอน deploy
# production:
#   primary: &primary_production
#     <<: *default
#     database: my_acadmy_quest_practice1_production
#     username: my_acadmy_quest_practice1
#     password: <%= ENV["MY_ACADMY_QUEST_PRACTICE1_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: my_acadmy_quest_practice1_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: my_acadmy_quest_practice1_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: my_acadmy_quest_practice1_production_cable
#     migrations_paths: db/cable_migrate